---
- google:    GOOGL
  apple:     AAPL
  microsoft: MSFT     
  amazon:    AMZN
  tesla:     TSLA
  walmart:   WMT
  netflix:   NFLX
  adobe:     ADBE
  nike:      NKE
  paypal:    PYPL
  qualcomm:  QCOM
  