---
development:
  API_HOST: http://localhost:9090
  DB_FILENAME: worker/infrastructure/database/local/dv.db
  AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
  AWS_REGION: ap-northeast-1
  ADD_QUEUE: PorfolioAdvisor-schedule-worker-test
  ADD_QUEUE_URL: ADD_QUEUE_URL
  GOOGLENEWS_TOKEN: GOOGLENEWS_TOKEN
  YAHOO_TOKEN: YAHOO_TOKEN
test:
  API_HOST: http://localhost:9090
  DB_FILENAME: worker/infrastructure/database/local/test.db
  AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
  AWS_REGION: ap-northeast-1
  ADD_QUEUE: PorfolioAdvisor-schedule-worker-test
  ADD_QUEUE_URL: ADD_QUEUE_URL
  GOOGLENEWS_TOKEN: GOOGLENEWS_TOKEN
  YAHOO_TOKEN: YAHOO_TOKEN

production:
  API_HOST: http://url.to.app
  AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
  AWS_REGION: ap-northeast-1
  ADD_QUEUE: PorfolioAdvisor-schedule-worker
  ADD_QUEUE_URL: ADD_QUEUE_URL
  GOOGLENEWS_TOKEN: GOOGLENEWS_TOKEN
  YAHOO_TOKEN: YAHOO_TOKEN